version: "1"

services:
  database:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rocco97%
      MYSQL_HOST: 0.0.0.0
      MYSQL_USER: utente
      MYSQL_PASSWORD: password
      MYSQL_DB: gtex
    volumes:
      - ./db/gtex.sql:/docker-entrypoint-initdb.d/gtex.sql
      - ./db/init_scripts:/docker-entrypoint-initdb.d/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - database
