import { Component, OnInit } from '@angular/core';

import { environment } from 'src/environments/environment';
import { HttpClient } from '@angular/common/http';

import * as XLSX from 'xlsx';

@Component({
  selector: 'app-query-builder',
  templateUrl: './query-builder.component.html',
  styleUrls: ['./query-builder.component.css']
})
export class QueryBuilderComponent implements OnInit {

  p:number = 1;

  constructor(private http:HttpClient) {
    this.tabellaScelta;
  }

   //Select
  ERRFI1:boolean = false;  
  MAD2L2:boolean = false;  
  MTHFR:boolean = false;  
  NPPA:boolean = false;  
  TNFRSF1B:boolean = false;  
  PLA2G2A:boolean = false;  
  ALPL:boolean = false;  
  HSPG2:boolean = false;  
  CNR2:boolean = false;  
  SLC9A1:boolean = false;  
  COL8A2:boolean = false;  
  CAP1:boolean = false;  
  SLC2A1:boolean = false;  
  CYP2J2:boolean = false;  
  DDAH1:boolean = false;  
  CYR61:boolean = false;  
  NGF:boolean = false;  
  HMGCS2:boolean = false;  
  CTSS:boolean = false;  
  S100A12:boolean = false;  
  LMNA:boolean = false;  
  CD247:boolean = false;  
  SELE:boolean = false;  
  FMO3:boolean = false;  
  PRDX6:boolean = false;  
  GLUL:boolean = false;  
  LAMC1:boolean = false;  
  PTGS2:boolean = false;  
  CHI3L1:boolean = false;  
  CHIT1:boolean = false;  
  FMOD:boolean = false;  
  IL10:boolean = false;  
  PFKFB2:boolean = false;  
  CD34:boolean = false;  
  COG2:boolean = false;  
  NLRP3:boolean = false;  
  ROCK2:boolean = false;  
  APOB:boolean = false;  
  POMC:boolean = false;  
  GCKR:boolean = false;  
  PLEKHH2:boolean = false;  
  PRKCE:boolean = false;  
  PIGF:boolean = false;  
  MSH2:boolean = false;  
  GFPT1:boolean = false;  
  TACR1:boolean = false;  
  REG1A:boolean = false;  
  EIF2AK3:boolean = false;  
  ADRA2B:boolean = false;  
  IL1B:boolean = false;  
  PROC:boolean = false;  
  POLR2D:boolean = false;  
  ZEB2:boolean = false;  
  ACVR1C:boolean = false;  
  DPP4:boolean = false;  
  NFE2L2:boolean = false;  
  IGFBP5:boolean = false;  
  CCL20:boolean = false;  
  HDAC4:boolean = false;  
  CAPN10:boolean = false;  
  GHRL:boolean = false;  
  PPARG:boolean = false;  
  RAF1:boolean = false;  
  MYD88:boolean = false;  
  CX3CR1:boolean = false;  
  CCK:boolean = false;  
  EXOSC7:boolean = false;  
  CCR1:boolean = false;  
  CCR5:boolean = false;  
  GPX1:boolean = false;  
  RHOA:boolean = false;  
  CISH:boolean = false;  
  TKT:boolean = false;  
  APPL1:boolean = false;  
  SLMAP:boolean = false;  
  COL8A1:boolean = false;  
  CD47:boolean = false;  
  GAP43:boolean = false;  
  CD80:boolean = false;  
  RHO:boolean = false;  
  TRH:boolean = false;  
  TF:boolean = false;  
  RBP1:boolean = false;  
  TRPC1:boolean = false;  
  AGTR1:boolean = false;  
  SUCNR1:boolean = false;  
  P2RY1:boolean = false;  
  MME:boolean = false;  
  SLC2A2:boolean = false;  
  PIK3CA:boolean = false;  
  PARL:boolean = false;  
  AHSG:boolean = false;  
  ADIPOQ:boolean = false;  
  SPON2:boolean = false;  
  WFS1:boolean = false;  
  CD38:boolean = false;  
  PROM1:boolean = false;  
  PPARGC1A:boolean = false;  
  IGFBP7:boolean = false;  
  CXCL5:boolean = false;  
  CXCL9:boolean = false;  
  CXCL10:boolean = false;  
  CXCL11:boolean = false;  
  HPSE:boolean = false;  
  SPP1:boolean = false;  
  ADH1B:boolean = false;  
  EGF:boolean = false;  
  ALPK1:boolean = false;  
  FABP2:boolean = false;  
  PDE5A:boolean = false;  
  SETD7:boolean = false;  
  SMAD1:boolean = false;  
  EDNRA:boolean = false;  
  NR3C2:boolean = false;  
  TLR2:boolean = false;  
  NPY5R:boolean = false;  
  FBXO8:boolean = false;  
  VEGFC:boolean = false;  
  ACSL1:boolean = false;  
  SORBS2:boolean = false;  
  F11:boolean = false;  
  BASP1:boolean = false;  
  PTGER4:boolean = false;  
  PRKAA1:boolean = false;  
  GHR:boolean = false;  
  ITGA2:boolean = false;  
  CDK7:boolean = false;  
  F2R:boolean = false;  
  ERAP2:boolean = false;  
  APC:boolean = false;  
  TNFAIP8:boolean = false;  
  VDAC1:boolean = false;  
  PDGFRB:boolean = false;  
  CD74:boolean = false;  
  SPARC:boolean = false;  
  EBF1:boolean = false;  
  GFPT2:boolean = false;  
  RREB1:boolean = false;  
  EDN1:boolean = false;  
  CDKAL1:boolean = false;  
  HFE:boolean = false;  
  HLA_A:boolean = false;  
  LTA:boolean = false;  
  TNF:boolean = false;  
  HSPA1A:boolean = false;  
  HSPA1B:boolean = false;  
  HLA_DQA1:boolean = false;  
  MAPK14:boolean = false;  
  CDKN1A:boolean = false;  
  GLO1:boolean = false;  
  VEGFA:boolean = false;  
  CD2AP:boolean = false;  
  CNR1:boolean = false;  
  ENPP1:boolean = false;  
  CTGF:boolean = false;  
  RPS12:boolean = false;  
  SGK1:boolean = false;  
  MAP3K5:boolean = false;  
  CITED2:boolean = false;  
  UTRN:boolean = false;  
  MTHFD1L:boolean = false;  
  VIP:boolean = false;  
  SOD2:boolean = false;  
  LPA:boolean = false;  
  THBS2:boolean = false;  
  PDGFA:boolean = false;  
  IL6:boolean = false;  
  NPY:boolean = false;  
  JAZF1:boolean = false;  
  CPVL:boolean = false;  
  AQP1:boolean = false;  
  ELMO1:boolean = false;  
  IGFBP3:boolean = false;  
  EGFR:boolean = false;  
  ELN:boolean = false;  
  NCF1:boolean = false;  
  HSPB1:boolean = false;  
  SEMA3A:boolean = false;  
  PON3:boolean = false;  
  PON2:boolean = false;  
  NAMPT:boolean = false;  
  CAV1:boolean = false;  
  LEP:boolean = false;  
  AKR1B1:boolean = false;  
  AKR1B10:boolean = false;  
  PIP:boolean = false;  
  RARRES2:boolean = false;  
  NOS3:boolean = false;  
  ANGPT2:boolean = false;  
  DEFA1:boolean = false;  
  LPL:boolean = false;  
  EBF2:boolean = false;  
  ADRB3:boolean = false;  
  EIF4EBP1:boolean = false;  
  FGFR1:boolean = false;  
  CRH:boolean = false;  
  SGK3:boolean = false;  
  FABP5:boolean = false;  
  FABP4:boolean = false;  
  MMP16:boolean = false;  
  NCALD:boolean = false;  
  KLF10:boolean = false;  
  ENPP2:boolean = false;  
  PVT1:boolean = false;  
  JAK2:boolean = false;  
  PSIP1:boolean = false;  
  PLIN2:boolean = false;  
  RPS6:boolean = false;  
  ALDH1A1:boolean = false;  
  FRMD3:boolean = false;  
  GAS1:boolean = false;  
  BAAT:boolean = false;  
  ABCA1:boolean = false;  
  TXN:boolean = false;  
  AMBP:boolean = false;  
  C5:boolean = false;  
  HSPA5:boolean = false;  
  ANGPTL2:boolean = false;  
  PTGES:boolean = false;  
  TSC1:boolean = false;  
  ABO:boolean = false;  
  ADAMTS13:boolean = false;  
  PTGDS:boolean = false;  
  KLF6:boolean = false;  
  CDC123:boolean = false;  
  BAMBI:boolean = false;  
  CXCL12:boolean = false;  
  MBL2:boolean = false;  
  TFAM:boolean = false;  
  SIRT1:boolean = false;  
  SRGN:boolean = false;  
  UNC5B:boolean = false;  
  ADK:boolean = false;  
  PTEN:boolean = false;  
  RBP4:boolean = false;  
  CYP2C19:boolean = false;  
  ENTPD1:boolean = false;  
  TCF7L2:boolean = false;  
  BNIP3:boolean = false;  
  IGF2:boolean = false;  
  INS:boolean = false;  
  TH:boolean = false;  
  KCNQ1:boolean = false;  
  HBG2:boolean = false;  
  SMPD1:boolean = false;  
  ILK:boolean = false;  
  ADM:boolean = false;  
  PTH:boolean = false;  
  NUCB2:boolean = false;  
  KCNJ11:boolean = false;  
  SAA1:boolean = false;  
  BDNF:boolean = false;  
  WT1:boolean = false;  
  CD59:boolean = false;  
  PDHX:boolean = false;  
  TRAF6:boolean = false;  
  API5:boolean = false;  
  NR1H3:boolean = false;  
  NDUFS3:boolean = false;  
  FOLH1:boolean = false;  
  APLNR:boolean = false;  
  P2RX3:boolean = false;  
  CNTF:boolean = false;  
  FADS1:boolean = false;  
  FADS2:boolean = false;  
  FKBP2:boolean = false;  
  SYVN1:boolean = false;  
  PC:boolean = false;  
  DHCR7:boolean = false;  
  PRCP:boolean = false;  
  NOX4:boolean = false;  
  PDGFD:boolean = false;  
  ATM:boolean = false;  
  IL18:boolean = false;  
  APOA1:boolean = false;  
  HYOU1:boolean = false;  
  ESAM:boolean = false;  
  FKBP4:boolean = false;  
  FGF23:boolean = false;  
  NTF3:boolean = false;  
  VWF:boolean = false;  
  CD9:boolean = false;  
  GAPDH:boolean = false;  
  CD4:boolean = false;  
  GNB3:boolean = false;  
  CD163:boolean = false;  
  SLC2A3:boolean = false;  
  CD69:boolean = false;  
  IRAK4:boolean = false;  
  VDR:boolean = false;  
  AQP5:boolean = false;  
  ACVRL1:boolean = false;  
  NFE2:boolean = false;  
  CD63:boolean = false;  
  ERBB3:boolean = false;  
  DDIT3:boolean = false;  
  IFNG:boolean = false;  
  NTS:boolean = false;  
  IGF1:boolean = false;  
  ACACB:boolean = false;  
  TRPV4:boolean = false;  
  ATP2A2:boolean = false;  
  ALDH2:boolean = false;  
  NOS1:boolean = false;  
  PEBP1:boolean = false;  
  PSMD9:boolean = false;  
  SCARB1:boolean = false;  
  P2RX2:boolean = false;  
  ALOX5AP:boolean = false;  
  KL:boolean = false;  
  POSTN:boolean = false;  
  FOXO1:boolean = false;  
  HTR2A:boolean = false;  
  GPC5:boolean = false;  
  IRS2:boolean = false;  
  GAS6:boolean = false;  
  ANG:boolean = false;  
  MMP14:boolean = false;  
  LTB4R2:boolean = false;  
  NFKBIA:boolean = false;  
  BMP4:boolean = false;  
  RTN1:boolean = false;  
  PGF:boolean = false;  
  NGB:boolean = false;  
  AHSA1:boolean = false;  
  BDKRB2:boolean = false;  
  BDKRB1:boolean = false;  
  AKT1:boolean = false;  
  GREM1:boolean = false;  
  THBS1:boolean = false;  
  PAK6:boolean = false;  
  B2M:boolean = false;  
  MYO5C:boolean = false;  
  ONECUT1:boolean = false;  
  ADAM10:boolean = false;  
  CTSH:boolean = false;  
  PLIN1:boolean = false;  
  IGF1R:boolean = false;  
  MRPL28:boolean = false;  
  CACNA1H:boolean = false;  
  PDPK1:boolean = false;  
  ERCC4:boolean = false;  
  SMG1:boolean = false;  
  ITGAM:boolean = false;  
  FTO:boolean = false;  
  MMP2:boolean = false;  
  SLC12A3:boolean = false;  
  CETP:boolean = false;  
  CX3CL1:boolean = false;  
  CDH1:boolean = false;  
  NQO1:boolean = false;  
  HP:boolean = false;  
  ZNRF1:boolean = false;  
  CYBA:boolean = false;  
  TUBB3:boolean = false;  
  CRK:boolean = false;  
  SERPINF2:boolean = false;  
  SERPINF1:boolean = false;  
  TRPV3:boolean = false;  
  CXCL16:boolean = false;  
  SLC2A4:boolean = false;  
  CD68:boolean = false;  
  SHBG:boolean = false;  
  PMP22:boolean = false;  
  SREBF1:boolean = false;  
  MAPK7:boolean = false;  
  CCL2:boolean = false;  
  CCL5:boolean = false;  
  HNF1B:boolean = false;  
  ERBB2:boolean = false;  
  FKBP10:boolean = false;  
  STAT5A:boolean = false;  
  STAT3:boolean = false;  
  NAGLU:boolean = false;  
  AOC2:boolean = false;  
  AOC3:boolean = false;  
  PPY:boolean = false;  
  STH:boolean = false;  
  ITGB3:boolean = false;  
  GIP:boolean = false;  
  MPO:boolean = false;  
  PECAM1:boolean = false;  
  SOX9:boolean = false;  
  TIMP2:boolean = false;  
  DCXR:boolean = false;  
  FASN:boolean = false;  
  COLEC12:boolean = false;  
  ADCYAP1:boolean = false;  
  SMAD7:boolean = false;  
  NEDD4L:boolean = false;  
  MC4R:boolean = false;  
  BCL2:boolean = false;  
  CNDP2:boolean = false;  
  ZNF236:boolean = false;  
  STK11:boolean = false;  
  SIRT6:boolean = false;  
  UHRF1:boolean = false;  
  TIMM44:boolean = false;  
  ANGPTL4:boolean = false;  
  DNMT1:boolean = false;  
  ICAM1:boolean = false;  
  LDLR:boolean = false;  
  EPOR:boolean = false;  
  PRDX2:boolean = false;  
  PTGER1:boolean = false;  
  UNC13A:boolean = false;  
  GDF15:boolean = false;  
  FKBP8:boolean = false;  
  USF2:boolean = false;  
  FFAR1:boolean = false;  
  FFAR2:boolean = false;  
  NPHS1:boolean = false;  
  TGFB1:boolean = false;  
  XRCC1:boolean = false;  
  ERCC1:boolean = false;  
  GIPR:boolean = false;  
  FGF21:boolean = false;  
  CLEC11A:boolean = false;  
  FPR1:boolean = false;  
  TRIB3:boolean = false;  
  BMP2:boolean = false;  
  THBD:boolean = false;  
  CST3:boolean = false;  
  ID1:boolean = false;  
  SRC:boolean = false;  
  MAFB:boolean = false;  
  SGK2:boolean = false;  
  HNF4A:boolean = false;  
  PLTP:boolean = false;  
  MMP9:boolean = false;  
  CD40:boolean = false;  
  PTPN1:boolean = false;  
  CYP24A1:boolean = false;  
  RCAN1:boolean = false;  
  ABCG1:boolean = false;  
  PRMT2:boolean = false;  
  COMT:boolean = false;  
  MAPK1:boolean = false;  
  MIF:boolean = false;  
  GGT1:boolean = false;  
  XBP1:boolean = false;  
  OSM:boolean = false;  
  LIMK2:boolean = false;  
  SFI1:boolean = false;  
  TIMP3:boolean = false;  
  HMOX1:boolean = false;  
  APOL1:boolean = false;  
  MYH9:boolean = false;  
  PDGFB:boolean = false;  
  ATF4:boolean = false;  
  TSPO:boolean = false;  
  MIOX:boolean = false;  
  PRDX4:boolean = false;  
  GK:boolean = false;  
  RGN:boolean = false;  
  TIMP1:boolean = false;  
  CLCN5:boolean = false;  
  AR:boolean = false;  
  FOXO4:boolean = false;  
  RPS6KA6:boolean = false;  
  NOX1:boolean = false;  
  XIAP:boolean = false;  
  CD40LG:boolean = false;  
  L1CAM:boolean = false;  
  IRAK1:boolean = false;  
  G6PD:boolean = false;  
  F8:boolean = false;  
  
  //from
  listaTabelle:any=[];
  tabellaScelta:any="";
  tessutoVisualizzato="";
  risultato:any=[];
  risultatoSenzaFiltri:any=[];
  disabled:boolean = false;

  //where
  sexFilter:any="";
  etaFilter:any="";

  //VisualizeOnly
  listColumns:any=[];

  page = 1;

  ngOnInit(): void {
    this.refreshList();
  }

  refreshList(){
    this.http.get<any>(environment.API_URL+'listaTabelle')
    .subscribe(data=>{
      this.listaTabelle=data;
    })
  }
  
  setTabella(elemento:any,tessuto:any){
    this.tessutoVisualizzato=tessuto;
    this.tabellaScelta=elemento;
  }

  clear(){
    window.location.reload();
  }

  showTable(){
    if(this.tabellaScelta!=null&&this.tabellaScelta!=""){
      this.disabled=true; //Disable tissue change
      this.popolizeTable(); //Choose the columns that i can see
      this.http.get<any>(environment.API_URL+this.tabellaScelta).subscribe(data=>{this.risultato=data;}) //Enjoy data with filter
      this.http.get<any>(environment.API_URL+this.tabellaScelta).subscribe(data=>{this.risultatoSenzaFiltri=data;}) //Enjoy data without filter
    }
    else{
      alert("Select at least one tissue!");
    }
  }

  FilterFn(){
    var SexFilter=this.sexFilter;
    var EtaFilter=this.etaFilter;
    this.risultato=this.risultatoSenzaFiltri.filter(
      function(el:any){
        return el.sesso.toString().toLowerCase().includes(SexFilter.toString().trim().toLowerCase())&&el.eta.toString().toLowerCase().includes(EtaFilter.toString().trim().toLowerCase())
      }
    );
  }

  exportexcel(): void 
    {
       /* table id is passed over here */   
       let element = document.getElementById('tableQuery'); 
       const ws: XLSX.WorkSheet =XLSX.utils.table_to_sheet(element);

       /* generate workbook and add the worksheet */
       const wb: XLSX.WorkBook = XLSX.utils.book_new();
       XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');

       /* save to file */
       XLSX.writeFile(wb, this.tessutoVisualizzato+".xlsx");
			
    }

    popolizeTable(){
      this.listColumns=[];
      this.listColumns.push('SUBJID');
      this.listColumns.push('SAMPID');
      this.listColumns.push('SEX');
      this.listColumns.push('AGE');
      if(this.ERRFI1){this.listColumns.push('ERRFI1')};
      if(this.MAD2L2){this.listColumns.push('MAD2L2')};
      if(this.MTHFR){this.listColumns.push('MTHFR')};
      if(this.NPPA){this.listColumns.push('NPPA')};
      if(this.TNFRSF1B){this.listColumns.push('TNFRSF1B')};
      if(this.PLA2G2A){this.listColumns.push('PLA2G2A')};
      if(this.ALPL){this.listColumns.push('ALPL')};
      if(this.HSPG2){this.listColumns.push('HSPG2')};
      if(this.CNR2){this.listColumns.push('CNR2')};
      if(this.SLC9A1){this.listColumns.push('SLC9A1')};
      if(this.COL8A2){this.listColumns.push('COL8A2')};
      if(this.CAP1){this.listColumns.push('CAP1')};
      if(this.SLC2A1){this.listColumns.push('SLC2A1')};
      if(this.CYP2J2){this.listColumns.push('CYP2J2')};
      if(this.DDAH1){this.listColumns.push('DDAH1')};
      if(this.CYR61){this.listColumns.push('CYR61')};
      if(this.NGF){this.listColumns.push('NGF')};
      if(this.HMGCS2){this.listColumns.push('HMGCS2')};
      if(this.CTSS){this.listColumns.push('CTSS')};
      if(this.S100A12){this.listColumns.push('S100A12')};
      if(this.LMNA){this.listColumns.push('LMNA')};
      if(this.CD247){this.listColumns.push('CD247')};
      if(this.SELE){this.listColumns.push('SELE')};
      if(this.FMO3){this.listColumns.push('FMO3')};
      if(this.PRDX6){this.listColumns.push('PRDX6')};
      if(this.GLUL){this.listColumns.push('GLUL')};
      if(this.LAMC1){this.listColumns.push('LAMC1')};
      if(this.PTGS2){this.listColumns.push('PTGS2')};
      if(this.CHI3L1){this.listColumns.push('CHI3L1')};
      if(this.CHIT1){this.listColumns.push('CHIT1')};
      if(this.FMOD){this.listColumns.push('FMOD')};
      if(this.IL10){this.listColumns.push('IL10')};
      if(this.PFKFB2){this.listColumns.push('PFKFB2')};
      if(this.CD34){this.listColumns.push('CD34')};
      if(this.COG2){this.listColumns.push('COG2')};
      if(this.NLRP3){this.listColumns.push('NLRP3')};
      if(this.ROCK2){this.listColumns.push('ROCK2')};
      if(this.APOB){this.listColumns.push('APOB')};
      if(this.POMC){this.listColumns.push('POMC')};
      if(this.GCKR){this.listColumns.push('GCKR')};
      if(this.PLEKHH2){this.listColumns.push('PLEKHH2')};
      if(this.PRKCE){this.listColumns.push('PRKCE')};
      if(this.PIGF){this.listColumns.push('PIGF')};
      if(this.MSH2){this.listColumns.push('MSH2')};
      if(this.GFPT1){this.listColumns.push('GFPT1')};
      if(this.TACR1){this.listColumns.push('TACR1')};
      if(this.REG1A){this.listColumns.push('REG1A')};
      if(this.EIF2AK3){this.listColumns.push('EIF2AK3')};
      if(this.ADRA2B){this.listColumns.push('ADRA2B')};
      if(this.IL1B){this.listColumns.push('IL1B')};
      if(this.PROC){this.listColumns.push('PROC')};
      if(this.POLR2D){this.listColumns.push('POLR2D')};
      if(this.ZEB2){this.listColumns.push('ZEB2')};
      if(this.ACVR1C){this.listColumns.push('ACVR1C')};
      if(this.DPP4){this.listColumns.push('DPP4')};
      if(this.NFE2L2){this.listColumns.push('NFE2L2')};
      if(this.IGFBP5){this.listColumns.push('IGFBP5')};
      if(this.CCL20){this.listColumns.push('CCL20')};
      if(this.HDAC4){this.listColumns.push('HDAC4')};
      if(this.CAPN10){this.listColumns.push('CAPN10')};
      if(this.GHRL){this.listColumns.push('GHRL')};
      if(this.PPARG){this.listColumns.push('PPARG')};
      if(this.RAF1){this.listColumns.push('RAF1')};
      if(this.MYD88){this.listColumns.push('MYD88')};
      if(this.CX3CR1){this.listColumns.push('CX3CR1')};
      if(this.CCK){this.listColumns.push('CCK')};
      if(this.EXOSC7){this.listColumns.push('EXOSC7')};
      if(this.CCR1){this.listColumns.push('CCR1')};
      if(this.CCR5){this.listColumns.push('CCR5')};
      if(this.GPX1){this.listColumns.push('GPX1')};
      if(this.RHOA){this.listColumns.push('RHOA')};
      if(this.CISH){this.listColumns.push('CISH')};
      if(this.TKT){this.listColumns.push('TKT')};
      if(this.APPL1){this.listColumns.push('APPL1')};
      if(this.SLMAP){this.listColumns.push('SLMAP')};
      if(this.COL8A1){this.listColumns.push('COL8A1')};
      if(this.CD47){this.listColumns.push('CD47')};
      if(this.GAP43){this.listColumns.push('GAP43')};
      if(this.CD80){this.listColumns.push('CD80')};
      if(this.RHO){this.listColumns.push('RHO')};
      if(this.TRH){this.listColumns.push('TRH')};
      if(this.TF){this.listColumns.push('TF')};
      if(this.RBP1){this.listColumns.push('RBP1')};
      if(this.TRPC1){this.listColumns.push('TRPC1')};
      if(this.AGTR1){this.listColumns.push('AGTR1')};
      if(this.SUCNR1){this.listColumns.push('SUCNR1')};
      if(this.P2RY1){this.listColumns.push('P2RY1')};
      if(this.MME){this.listColumns.push('MME')};
      if(this.SLC2A2){this.listColumns.push('SLC2A2')};
      if(this.PIK3CA){this.listColumns.push('PIK3CA')};
      if(this.PARL){this.listColumns.push('PARL')};
      if(this.AHSG){this.listColumns.push('AHSG')};
      if(this.ADIPOQ){this.listColumns.push('ADIPOQ')};
      if(this.SPON2){this.listColumns.push('SPON2')};
      if(this.WFS1){this.listColumns.push('WFS1')};
      if(this.CD38){this.listColumns.push('CD38')};
      if(this.PROM1){this.listColumns.push('PROM1')};
      if(this.PPARGC1A){this.listColumns.push('PPARGC1A')};
      if(this.IGFBP7){this.listColumns.push('IGFBP7')};
      if(this.CXCL5){this.listColumns.push('CXCL5')};
      if(this.CXCL9){this.listColumns.push('CXCL9')};
      if(this.CXCL10){this.listColumns.push('CXCL10')};
      if(this.CXCL11){this.listColumns.push('CXCL11')};
      if(this.HPSE){this.listColumns.push('HPSE')};
      if(this.SPP1){this.listColumns.push('SPP1')};
      if(this.ADH1B){this.listColumns.push('ADH1B')};
      if(this.EGF){this.listColumns.push('EGF')};
      if(this.ALPK1){this.listColumns.push('ALPK1')};
      if(this.FABP2){this.listColumns.push('FABP2')};
      if(this.PDE5A){this.listColumns.push('PDE5A')};
      if(this.SETD7){this.listColumns.push('SETD7')};
      if(this.SMAD1){this.listColumns.push('SMAD1')};
      if(this.EDNRA){this.listColumns.push('EDNRA')};
      if(this.NR3C2){this.listColumns.push('NR3C2')};
      if(this.TLR2){this.listColumns.push('TLR2')};
      if(this.NPY5R){this.listColumns.push('NPY5R')};
      if(this.FBXO8){this.listColumns.push('FBXO8')};
      if(this.VEGFC){this.listColumns.push('VEGFC')};
      if(this.ACSL1){this.listColumns.push('ACSL1')};
      if(this.SORBS2){this.listColumns.push('SORBS2')};
      if(this.F11){this.listColumns.push('F11')};
      if(this.BASP1){this.listColumns.push('BASP1')};
      if(this.PTGER4){this.listColumns.push('PTGER4')};
      if(this.PRKAA1){this.listColumns.push('PRKAA1')};
      if(this.GHR){this.listColumns.push('GHR')};
      if(this.ITGA2){this.listColumns.push('ITGA2')};
      if(this.CDK7){this.listColumns.push('CDK7')};
      if(this.F2R){this.listColumns.push('F2R')};
      if(this.ERAP2){this.listColumns.push('ERAP2')};
      if(this.APC){this.listColumns.push('APC')};
      if(this.TNFAIP8){this.listColumns.push('TNFAIP8')};
      if(this.VDAC1){this.listColumns.push('VDAC1')};
      if(this.PDGFRB){this.listColumns.push('PDGFRB')};
      if(this.CD74){this.listColumns.push('CD74')};
      if(this.SPARC){this.listColumns.push('SPARC')};
      if(this.EBF1){this.listColumns.push('EBF1')};
      if(this.GFPT2){this.listColumns.push('GFPT2')};
      if(this.RREB1){this.listColumns.push('RREB1')};
      if(this.EDN1){this.listColumns.push('EDN1')};
      if(this.CDKAL1){this.listColumns.push('CDKAL1')};
      if(this.HFE){this.listColumns.push('HFE')};
      if(this.HLA_A){this.listColumns.push('HLA_A')};
      if(this.LTA){this.listColumns.push('LTA')};
      if(this.TNF){this.listColumns.push('TNF')};
      if(this.HSPA1A){this.listColumns.push('HSPA1A')};
      if(this.HSPA1B){this.listColumns.push('HSPA1B')};
      if(this.HLA_DQA1){this.listColumns.push('HLA_DQA1')};
      if(this.MAPK14){this.listColumns.push('MAPK14')};
      if(this.CDKN1A){this.listColumns.push('CDKN1A')};
      if(this.GLO1){this.listColumns.push('GLO1')};
      if(this.VEGFA){this.listColumns.push('VEGFA')};
      if(this.CD2AP){this.listColumns.push('CD2AP')};
      if(this.CNR1){this.listColumns.push('CNR1')};
      if(this.ENPP1){this.listColumns.push('ENPP1')};
      if(this.CTGF){this.listColumns.push('CTGF')};
      if(this.RPS12){this.listColumns.push('RPS12')};
      if(this.SGK1){this.listColumns.push('SGK1')};
      if(this.MAP3K5){this.listColumns.push('MAP3K5')};
      if(this.CITED2){this.listColumns.push('CITED2')};
      if(this.UTRN){this.listColumns.push('UTRN')};
      if(this.MTHFD1L){this.listColumns.push('MTHFD1L')};
      if(this.VIP){this.listColumns.push('VIP')};
      if(this.SOD2){this.listColumns.push('SOD2')};
      if(this.LPA){this.listColumns.push('LPA')};
      if(this.THBS2){this.listColumns.push('THBS2')};
      if(this.PDGFA){this.listColumns.push('PDGFA')};
      if(this.IL6){this.listColumns.push('IL6')};
      if(this.NPY){this.listColumns.push('NPY')};
      if(this.JAZF1){this.listColumns.push('JAZF1')};
      if(this.CPVL){this.listColumns.push('CPVL')};
      if(this.AQP1){this.listColumns.push('AQP1')};
      if(this.ELMO1){this.listColumns.push('ELMO1')};
      if(this.IGFBP3){this.listColumns.push('IGFBP3')};
      if(this.EGFR){this.listColumns.push('EGFR')};
      if(this.ELN){this.listColumns.push('ELN')};
      if(this.NCF1){this.listColumns.push('NCF1')};
      if(this.HSPB1){this.listColumns.push('HSPB1')};
      if(this.SEMA3A){this.listColumns.push('SEMA3A')};
      if(this.PON3){this.listColumns.push('PON3')};
      if(this.PON2){this.listColumns.push('PON2')};
      if(this.NAMPT){this.listColumns.push('NAMPT')};
      if(this.CAV1){this.listColumns.push('CAV1')};
      if(this.LEP){this.listColumns.push('LEP')};
      if(this.AKR1B1){this.listColumns.push('AKR1B1')};
      if(this.AKR1B10){this.listColumns.push('AKR1B10')};
      if(this.PIP){this.listColumns.push('PIP')};
      if(this.RARRES2){this.listColumns.push('RARRES2')};
      if(this.NOS3){this.listColumns.push('NOS3')};
      if(this.ANGPT2){this.listColumns.push('ANGPT2')};
      if(this.DEFA1){this.listColumns.push('DEFA1')};
      if(this.LPL){this.listColumns.push('LPL')};
      if(this.EBF2){this.listColumns.push('EBF2')};
      if(this.ADRB3){this.listColumns.push('ADRB3')};
      if(this.EIF4EBP1){this.listColumns.push('EIF4EBP1')};
      if(this.FGFR1){this.listColumns.push('FGFR1')};
      if(this.CRH){this.listColumns.push('CRH')};
      if(this.SGK3){this.listColumns.push('SGK3')};
      if(this.FABP5){this.listColumns.push('FABP5')};
      if(this.FABP4){this.listColumns.push('FABP4')};
      if(this.MMP16){this.listColumns.push('MMP16')};
      if(this.NCALD){this.listColumns.push('NCALD')};
      if(this.KLF10){this.listColumns.push('KLF10')};
      if(this.ENPP2){this.listColumns.push('ENPP2')};
      if(this.PVT1){this.listColumns.push('PVT1')};
      if(this.JAK2){this.listColumns.push('JAK2')};
      if(this.PSIP1){this.listColumns.push('PSIP1')};
      if(this.PLIN2){this.listColumns.push('PLIN2')};
      if(this.RPS6){this.listColumns.push('RPS6')};
      if(this.ALDH1A1){this.listColumns.push('ALDH1A1')};
      if(this.FRMD3){this.listColumns.push('FRMD3')};
      if(this.GAS1){this.listColumns.push('GAS1')};
      if(this.BAAT){this.listColumns.push('BAAT')};
      if(this.ABCA1){this.listColumns.push('ABCA1')};
      if(this.TXN){this.listColumns.push('TXN')};
      if(this.AMBP){this.listColumns.push('AMBP')};
      if(this.C5){this.listColumns.push('C5')};
      if(this.HSPA5){this.listColumns.push('HSPA5')};
      if(this.ANGPTL2){this.listColumns.push('ANGPTL2')};
      if(this.PTGES){this.listColumns.push('PTGES')};
      if(this.TSC1){this.listColumns.push('TSC1')};
      if(this.ABO){this.listColumns.push('ABO')};
      if(this.ADAMTS13){this.listColumns.push('ADAMTS13')};
      if(this.PTGDS){this.listColumns.push('PTGDS')};
      if(this.KLF6){this.listColumns.push('KLF6')};
      if(this.CDC123){this.listColumns.push('CDC123')};
      if(this.BAMBI){this.listColumns.push('BAMBI')};
      if(this.CXCL12){this.listColumns.push('CXCL12')};
      if(this.MBL2){this.listColumns.push('MBL2')};
      if(this.TFAM){this.listColumns.push('TFAM')};
      if(this.SIRT1){this.listColumns.push('SIRT1')};
      if(this.SRGN){this.listColumns.push('SRGN')};
      if(this.UNC5B){this.listColumns.push('UNC5B')};
      if(this.ADK){this.listColumns.push('ADK')};
      if(this.PTEN){this.listColumns.push('PTEN')};
      if(this.RBP4){this.listColumns.push('RBP4')};
      if(this.CYP2C19){this.listColumns.push('CYP2C19')};
      if(this.ENTPD1){this.listColumns.push('ENTPD1')};
      if(this.TCF7L2){this.listColumns.push('TCF7L2')};
      if(this.BNIP3){this.listColumns.push('BNIP3')};
      if(this.IGF2){this.listColumns.push('IGF2')};
      if(this.INS){this.listColumns.push('INS')};
      if(this.TH){this.listColumns.push('TH')};
      if(this.KCNQ1){this.listColumns.push('KCNQ1')};
      if(this.HBG2){this.listColumns.push('HBG2')};
      if(this.SMPD1){this.listColumns.push('SMPD1')};
      if(this.ILK){this.listColumns.push('ILK')};
      if(this.ADM){this.listColumns.push('ADM')};
      if(this.PTH){this.listColumns.push('PTH')};
      if(this.NUCB2){this.listColumns.push('NUCB2')};
      if(this.KCNJ11){this.listColumns.push('KCNJ11')};
      if(this.SAA1){this.listColumns.push('SAA1')};
      if(this.BDNF){this.listColumns.push('BDNF')};
      if(this.WT1){this.listColumns.push('WT1')};
      if(this.CD59){this.listColumns.push('CD59')};
      if(this.PDHX){this.listColumns.push('PDHX')};
      if(this.TRAF6){this.listColumns.push('TRAF6')};
      if(this.API5){this.listColumns.push('API5')};
      if(this.NR1H3){this.listColumns.push('NR1H3')};
      if(this.NDUFS3){this.listColumns.push('NDUFS3')};
      if(this.FOLH1){this.listColumns.push('FOLH1')};
      if(this.APLNR){this.listColumns.push('APLNR')};
      if(this.P2RX3){this.listColumns.push('P2RX3')};
      if(this.CNTF){this.listColumns.push('CNTF')};
      if(this.FADS1){this.listColumns.push('FADS1')};
      if(this.FADS2){this.listColumns.push('FADS2')};
      if(this.FKBP2){this.listColumns.push('FKBP2')};
      if(this.SYVN1){this.listColumns.push('SYVN1')};
      if(this.PC){this.listColumns.push('PC')};
      if(this.DHCR7){this.listColumns.push('DHCR7')};
      if(this.PRCP){this.listColumns.push('PRCP')};
      if(this.NOX4){this.listColumns.push('NOX4')};
      if(this.PDGFD){this.listColumns.push('PDGFD')};
      if(this.ATM){this.listColumns.push('ATM')};
      if(this.IL18){this.listColumns.push('IL18')};
      if(this.APOA1){this.listColumns.push('APOA1')};
      if(this.HYOU1){this.listColumns.push('HYOU1')};
      if(this.ESAM){this.listColumns.push('ESAM')};
      if(this.FKBP4){this.listColumns.push('FKBP4')};
      if(this.FGF23){this.listColumns.push('FGF23')};
      if(this.NTF3){this.listColumns.push('NTF3')};
      if(this.VWF){this.listColumns.push('VWF')};
      if(this.CD9){this.listColumns.push('CD9')};
      if(this.GAPDH){this.listColumns.push('GAPDH')};
      if(this.CD4){this.listColumns.push('CD4')};
      if(this.GNB3){this.listColumns.push('GNB3')};
      if(this.CD163){this.listColumns.push('CD163')};
      if(this.SLC2A3){this.listColumns.push('SLC2A3')};
      if(this.CD69){this.listColumns.push('CD69')};
      if(this.IRAK4){this.listColumns.push('IRAK4')};
      if(this.VDR){this.listColumns.push('VDR')};
      if(this.AQP5){this.listColumns.push('AQP5')};
      if(this.ACVRL1){this.listColumns.push('ACVRL1')};
      if(this.NFE2){this.listColumns.push('NFE2')};
      if(this.CD63){this.listColumns.push('CD63')};
      if(this.ERBB3){this.listColumns.push('ERBB3')};
      if(this.DDIT3){this.listColumns.push('DDIT3')};
      if(this.IFNG){this.listColumns.push('IFNG')};
      if(this.NTS){this.listColumns.push('NTS')};
      if(this.IGF1){this.listColumns.push('IGF1')};
      if(this.ACACB){this.listColumns.push('ACACB')};
      if(this.TRPV4){this.listColumns.push('TRPV4')};
      if(this.ATP2A2){this.listColumns.push('ATP2A2')};
      if(this.ALDH2){this.listColumns.push('ALDH2')};
      if(this.NOS1){this.listColumns.push('NOS1')};
      if(this.PEBP1){this.listColumns.push('PEBP1')};
      if(this.PSMD9){this.listColumns.push('PSMD9')};
      if(this.SCARB1){this.listColumns.push('SCARB1')};
      if(this.P2RX2){this.listColumns.push('P2RX2')};
      if(this.ALOX5AP){this.listColumns.push('ALOX5AP')};
      if(this.KL){this.listColumns.push('KL')};
      if(this.POSTN){this.listColumns.push('POSTN')};
      if(this.FOXO1){this.listColumns.push('FOXO1')};
      if(this.HTR2A){this.listColumns.push('HTR2A')};
      if(this.GPC5){this.listColumns.push('GPC5')};
      if(this.IRS2){this.listColumns.push('IRS2')};
      if(this.GAS6){this.listColumns.push('GAS6')};
      if(this.ANG){this.listColumns.push('ANG')};
      if(this.MMP14){this.listColumns.push('MMP14')};
      if(this.LTB4R2){this.listColumns.push('LTB4R2')};
      if(this.NFKBIA){this.listColumns.push('NFKBIA')};
      if(this.BMP4){this.listColumns.push('BMP4')};
      if(this.RTN1){this.listColumns.push('RTN1')};
      if(this.PGF){this.listColumns.push('PGF')};
      if(this.NGB){this.listColumns.push('NGB')};
      if(this.AHSA1){this.listColumns.push('AHSA1')};
      if(this.BDKRB2){this.listColumns.push('BDKRB2')};
      if(this.BDKRB1){this.listColumns.push('BDKRB1')};
      if(this.AKT1){this.listColumns.push('AKT1')};
      if(this.GREM1){this.listColumns.push('GREM1')};
      if(this.THBS1){this.listColumns.push('THBS1')};
      if(this.PAK6){this.listColumns.push('PAK6')};
      if(this.B2M){this.listColumns.push('B2M')};
      if(this.MYO5C){this.listColumns.push('MYO5C')};
      if(this.ONECUT1){this.listColumns.push('ONECUT1')};
      if(this.ADAM10){this.listColumns.push('ADAM10')};
      if(this.CTSH){this.listColumns.push('CTSH')};
      if(this.PLIN1){this.listColumns.push('PLIN1')};
      if(this.IGF1R){this.listColumns.push('IGF1R')};
      if(this.MRPL28){this.listColumns.push('MRPL28')};
      if(this.CACNA1H){this.listColumns.push('CACNA1H')};
      if(this.PDPK1){this.listColumns.push('PDPK1')};
      if(this.ERCC4){this.listColumns.push('ERCC4')};
      if(this.SMG1){this.listColumns.push('SMG1')};
      if(this.ITGAM){this.listColumns.push('ITGAM')};
      if(this.FTO){this.listColumns.push('FTO')};
      if(this.MMP2){this.listColumns.push('MMP2')};
      if(this.SLC12A3){this.listColumns.push('SLC12A3')};
      if(this.CETP){this.listColumns.push('CETP')};
      if(this.CX3CL1){this.listColumns.push('CX3CL1')};
      if(this.CDH1){this.listColumns.push('CDH1')};
      if(this.NQO1){this.listColumns.push('NQO1')};
      if(this.HP){this.listColumns.push('HP')};
      if(this.ZNRF1){this.listColumns.push('ZNRF1')};
      if(this.CYBA){this.listColumns.push('CYBA')};
      if(this.TUBB3){this.listColumns.push('TUBB3')};
      if(this.CRK){this.listColumns.push('CRK')};
      if(this.SERPINF2){this.listColumns.push('SERPINF2')};
      if(this.SERPINF1){this.listColumns.push('SERPINF1')};
      if(this.TRPV3){this.listColumns.push('TRPV3')};
      if(this.CXCL16){this.listColumns.push('CXCL16')};
      if(this.SLC2A4){this.listColumns.push('SLC2A4')};
      if(this.CD68){this.listColumns.push('CD68')};
      if(this.SHBG){this.listColumns.push('SHBG')};
      if(this.PMP22){this.listColumns.push('PMP22')};
      if(this.SREBF1){this.listColumns.push('SREBF1')};
      if(this.MAPK7){this.listColumns.push('MAPK7')};
      if(this.CCL2){this.listColumns.push('CCL2')};
      if(this.CCL5){this.listColumns.push('CCL5')};
      if(this.HNF1B){this.listColumns.push('HNF1B')};
      if(this.ERBB2){this.listColumns.push('ERBB2')};
      if(this.FKBP10){this.listColumns.push('FKBP10')};
      if(this.STAT5A){this.listColumns.push('STAT5A')};
      if(this.STAT3){this.listColumns.push('STAT3')};
      if(this.NAGLU){this.listColumns.push('NAGLU')};
      if(this.AOC2){this.listColumns.push('AOC2')};
      if(this.AOC3){this.listColumns.push('AOC3')};
      if(this.PPY){this.listColumns.push('PPY')};
      if(this.STH){this.listColumns.push('STH')};
      if(this.ITGB3){this.listColumns.push('ITGB3')};
      if(this.GIP){this.listColumns.push('GIP')};
      if(this.MPO){this.listColumns.push('MPO')};
      if(this.PECAM1){this.listColumns.push('PECAM1')};
      if(this.SOX9){this.listColumns.push('SOX9')};
      if(this.TIMP2){this.listColumns.push('TIMP2')};
      if(this.DCXR){this.listColumns.push('DCXR')};
      if(this.FASN){this.listColumns.push('FASN')};
      if(this.COLEC12){this.listColumns.push('COLEC12')};
      if(this.ADCYAP1){this.listColumns.push('ADCYAP1')};
      if(this.SMAD7){this.listColumns.push('SMAD7')};
      if(this.NEDD4L){this.listColumns.push('NEDD4L')};
      if(this.MC4R){this.listColumns.push('MC4R')};
      if(this.BCL2){this.listColumns.push('BCL2')};
      if(this.CNDP2){this.listColumns.push('CNDP2')};
      if(this.ZNF236){this.listColumns.push('ZNF236')};
      if(this.STK11){this.listColumns.push('STK11')};
      if(this.SIRT6){this.listColumns.push('SIRT6')};
      if(this.UHRF1){this.listColumns.push('UHRF1')};
      if(this.TIMM44){this.listColumns.push('TIMM44')};
      if(this.ANGPTL4){this.listColumns.push('ANGPTL4')};
      if(this.DNMT1){this.listColumns.push('DNMT1')};
      if(this.ICAM1){this.listColumns.push('ICAM1')};
      if(this.LDLR){this.listColumns.push('LDLR')};
      if(this.EPOR){this.listColumns.push('EPOR')};
      if(this.PRDX2){this.listColumns.push('PRDX2')};
      if(this.PTGER1){this.listColumns.push('PTGER1')};
      if(this.UNC13A){this.listColumns.push('UNC13A')};
      if(this.GDF15){this.listColumns.push('GDF15')};
      if(this.FKBP8){this.listColumns.push('FKBP8')};
      if(this.USF2){this.listColumns.push('USF2')};
      if(this.FFAR1){this.listColumns.push('FFAR1')};
      if(this.FFAR2){this.listColumns.push('FFAR2')};
      if(this.NPHS1){this.listColumns.push('NPHS1')};
      if(this.TGFB1){this.listColumns.push('TGFB1')};
      if(this.XRCC1){this.listColumns.push('XRCC1')};
      if(this.ERCC1){this.listColumns.push('ERCC1')};
      if(this.GIPR){this.listColumns.push('GIPR')};
      if(this.FGF21){this.listColumns.push('FGF21')};
      if(this.CLEC11A){this.listColumns.push('CLEC11A')};
      if(this.FPR1){this.listColumns.push('FPR1')};
      if(this.TRIB3){this.listColumns.push('TRIB3')};
      if(this.BMP2){this.listColumns.push('BMP2')};
      if(this.THBD){this.listColumns.push('THBD')};
      if(this.CST3){this.listColumns.push('CST3')};
      if(this.ID1){this.listColumns.push('ID1')};
      if(this.SRC){this.listColumns.push('SRC')};
      if(this.MAFB){this.listColumns.push('MAFB')};
      if(this.SGK2){this.listColumns.push('SGK2')};
      if(this.HNF4A){this.listColumns.push('HNF4A')};
      if(this.PLTP){this.listColumns.push('PLTP')};
      if(this.MMP9){this.listColumns.push('MMP9')};
      if(this.CD40){this.listColumns.push('CD40')};
      if(this.PTPN1){this.listColumns.push('PTPN1')};
      if(this.CYP24A1){this.listColumns.push('CYP24A1')};
      if(this.RCAN1){this.listColumns.push('RCAN1')};
      if(this.ABCG1){this.listColumns.push('ABCG1')};
      if(this.PRMT2){this.listColumns.push('PRMT2')};
      if(this.COMT){this.listColumns.push('COMT')};
      if(this.MAPK1){this.listColumns.push('MAPK1')};
      if(this.MIF){this.listColumns.push('MIF')};
      if(this.GGT1){this.listColumns.push('GGT1')};
      if(this.XBP1){this.listColumns.push('XBP1')};
      if(this.OSM){this.listColumns.push('OSM')};
      if(this.LIMK2){this.listColumns.push('LIMK2')};
      if(this.SFI1){this.listColumns.push('SFI1')};
      if(this.TIMP3){this.listColumns.push('TIMP3')};
      if(this.HMOX1){this.listColumns.push('HMOX1')};
      if(this.APOL1){this.listColumns.push('APOL1')};
      if(this.MYH9){this.listColumns.push('MYH9')};
      if(this.PDGFB){this.listColumns.push('PDGFB')};
      if(this.ATF4){this.listColumns.push('ATF4')};
      if(this.TSPO){this.listColumns.push('TSPO')};
      if(this.MIOX){this.listColumns.push('MIOX')};
      if(this.PRDX4){this.listColumns.push('PRDX4')};
      if(this.GK){this.listColumns.push('GK')};
      if(this.RGN){this.listColumns.push('RGN')};
      if(this.TIMP1){this.listColumns.push('TIMP1')};
      if(this.CLCN5){this.listColumns.push('CLCN5')};
      if(this.AR){this.listColumns.push('AR')};
      if(this.FOXO4){this.listColumns.push('FOXO4')};
      if(this.RPS6KA6){this.listColumns.push('RPS6KA6')};
      if(this.NOX1){this.listColumns.push('NOX1')};
      if(this.XIAP){this.listColumns.push('XIAP')};
      if(this.CD40LG){this.listColumns.push('CD40LG')};
      if(this.L1CAM){this.listColumns.push('L1CAM')};
      if(this.IRAK1){this.listColumns.push('IRAK1')};
      if(this.G6PD){this.listColumns.push('G6PD')};
      if(this.F8){this.listColumns.push('F8')};
    }

    selectAll(){
        this.ERRFI1 = true;
        this.MAD2L2 = true;
        this.MTHFR = true;
        this.NPPA = true;
        this.TNFRSF1B = true;
        this.PLA2G2A = true;
        this.ALPL = true;
        this.HSPG2 = true;
        this.CNR2 = true;
        this.SLC9A1 = true;
        this.COL8A2 = true;
        this.CAP1 = true;
        this.SLC2A1 = true;
        this.CYP2J2 = true;
        this.DDAH1 = true;
        this.CYR61 = true;
        this.NGF = true;
        this.HMGCS2 = true;
        this.CTSS = true;
        this.S100A12 = true;
        this.LMNA = true;
        this.CD247 = true;
        this.SELE = true;
        this.FMO3 = true;
        this.PRDX6 = true;
        this.GLUL = true;
        this.LAMC1 = true;
        this.PTGS2 = true;
        this.CHI3L1 = true;
        this.CHIT1 = true;
        this.FMOD = true;
        this.IL10 = true;
        this.PFKFB2 = true;
        this.CD34 = true;
        this.COG2 = true;
        this.NLRP3 = true;
        this.ROCK2 = true;
        this.APOB = true;
        this.POMC = true;
        this.GCKR = true;
        this.PLEKHH2 = true;
        this.PRKCE = true;
        this.PIGF = true;
        this.MSH2 = true;
        this.GFPT1 = true;
        this.TACR1 = true;
        this.REG1A = true;
        this.EIF2AK3 = true;
        this.ADRA2B = true;
        this.IL1B = true;
        this.PROC = true;
        this.POLR2D = true;
        this.ZEB2 = true;
        this.ACVR1C = true;
        this.DPP4 = true;
        this.NFE2L2 = true;
        this.IGFBP5 = true;
        this.CCL20 = true;
        this.HDAC4 = true;
        this.CAPN10 = true;
        this.GHRL = true;
        this.PPARG = true;
        this.RAF1 = true;
        this.MYD88 = true;
        this.CX3CR1 = true;
        this.CCK = true;
        this.EXOSC7 = true;
        this.CCR1 = true;
        this.CCR5 = true;
        this.GPX1 = true;
        this.RHOA = true;
        this.CISH = true;
        this.TKT = true;
        this.APPL1 = true;
        this.SLMAP = true;
        this.COL8A1 = true;
        this.CD47 = true;
        this.GAP43 = true;
        this.CD80 = true;
        this.RHO = true;
        this.TRH = true;
        this.TF = true;
        this.RBP1 = true;
        this.TRPC1 = true;
        this.AGTR1 = true;
        this.SUCNR1 = true;
        this.P2RY1 = true;
        this.MME = true;
        this.SLC2A2 = true;
        this.PIK3CA = true;
        this.PARL = true;
        this.AHSG = true;
        this.ADIPOQ = true;
        this.SPON2 = true;
        this.WFS1 = true;
        this.CD38 = true;
        this.PROM1 = true;
        this.PPARGC1A = true;
        this.IGFBP7 = true;
        this.CXCL5 = true;
        this.CXCL9 = true;
        this.CXCL10 = true;
        this.CXCL11 = true;
        this.HPSE = true;
        this.SPP1 = true;
        this.ADH1B = true;
        this.EGF = true;
        this.ALPK1 = true;
        this.FABP2 = true;
        this.PDE5A = true;
        this.SETD7 = true;
        this.SMAD1 = true;
        this.EDNRA = true;
        this.NR3C2 = true;
        this.TLR2 = true;
        this.NPY5R = true;
        this.FBXO8 = true;
        this.VEGFC = true;
        this.ACSL1 = true;
        this.SORBS2 = true;
        this.F11 = true;
        this.BASP1 = true;
        this.PTGER4 = true;
        this.PRKAA1 = true;
        this.GHR = true;
        this.ITGA2 = true;
        this.CDK7 = true;
        this.F2R = true;
        this.ERAP2 = true;
        this.APC = true;
        this.TNFAIP8 = true;
        this.VDAC1 = true;
        this.PDGFRB = true;
        this.CD74 = true;
        this.SPARC = true;
        this.EBF1 = true;
        this.GFPT2 = true;
        this.RREB1 = true;
        this.EDN1 = true;
        this.CDKAL1 = true;
        this.HFE = true;
        this.HLA_A = true;
        this.LTA = true;
        this.TNF = true;
        this.HSPA1A = true;
        this.HSPA1B = true;
        this.HLA_DQA1 = true;
        this.MAPK14 = true;
        this.CDKN1A = true;
        this.GLO1 = true;
        this.VEGFA = true;
        this.CD2AP = true;
        this.CNR1 = true;
        this.ENPP1 = true;
        this.CTGF = true;
        this.RPS12 = true;
        this.SGK1 = true;
        this.MAP3K5 = true;
        this.CITED2 = true;
        this.UTRN = true;
        this.MTHFD1L = true;
        this.VIP = true;
        this.SOD2 = true;
        this.LPA = true;
        this.THBS2 = true;
        this.PDGFA = true;
        this.IL6 = true;
        this.NPY = true;
        this.JAZF1 = true;
        this.CPVL = true;
        this.AQP1 = true;
        this.ELMO1 = true;
        this.IGFBP3 = true;
        this.EGFR = true;
        this.ELN = true;
        this.NCF1 = true;
        this.HSPB1 = true;
        this.SEMA3A = true;
        this.PON3 = true;
        this.PON2 = true;
        this.NAMPT = true;
        this.CAV1 = true;
        this.LEP = true;
        this.AKR1B1 = true;
        this.AKR1B10 = true;
        this.PIP = true;
        this.RARRES2 = true;
        this.NOS3 = true;
        this.ANGPT2 = true;
        this.DEFA1 = true;
        this.LPL = true;
        this.EBF2 = true;
        this.ADRB3 = true;
        this.EIF4EBP1 = true;
        this.FGFR1 = true;
        this.CRH = true;
        this.SGK3 = true;
        this.FABP5 = true;
        this.FABP4 = true;
        this.MMP16 = true;
        this.NCALD = true;
        this.KLF10 = true;
        this.ENPP2 = true;
        this.PVT1 = true;
        this.JAK2 = true;
        this.PSIP1 = true;
        this.PLIN2 = true;
        this.RPS6 = true;
        this.ALDH1A1 = true;
        this.FRMD3 = true;
        this.GAS1 = true;
        this.BAAT = true;
        this.ABCA1 = true;
        this.TXN = true;
        this.AMBP = true;
        this.C5 = true;
        this.HSPA5 = true;
        this.ANGPTL2 = true;
        this.PTGES = true;
        this.TSC1 = true;
        this.ABO = true;
        this.ADAMTS13 = true;
        this.PTGDS = true;
        this.KLF6 = true;
        this.CDC123 = true;
        this.BAMBI = true;
        this.CXCL12 = true;
        this.MBL2 = true;
        this.TFAM = true;
        this.SIRT1 = true;
        this.SRGN = true;
        this.UNC5B = true;
        this.ADK = true;
        this.PTEN = true;
        this.RBP4 = true;
        this.CYP2C19 = true;
        this.ENTPD1 = true;
        this.TCF7L2 = true;
        this.BNIP3 = true;
        this.IGF2 = true;
        this.INS = true;
        this.TH = true;
        this.KCNQ1 = true;
        this.HBG2 = true;
        this.SMPD1 = true;
        this.ILK = true;
        this.ADM = true;
        this.PTH = true;
        this.NUCB2 = true;
        this.KCNJ11 = true;
        this.SAA1 = true;
        this.BDNF = true;
        this.WT1 = true;
        this.CD59 = true;
        this.PDHX = true;
        this.TRAF6 = true;
        this.API5 = true;
        this.NR1H3 = true;
        this.NDUFS3 = true;
        this.FOLH1 = true;
        this.APLNR = true;
        this.P2RX3 = true;
        this.CNTF = true;
        this.FADS1 = true;
        this.FADS2 = true;
        this.FKBP2 = true;
        this.SYVN1 = true;
        this.PC = true;
        this.DHCR7 = true;
        this.PRCP = true;
        this.NOX4 = true;
        this.PDGFD = true;
        this.ATM = true;
        this.IL18 = true;
        this.APOA1 = true;
        this.HYOU1 = true;
        this.ESAM = true;
        this.FKBP4 = true;
        this.FGF23 = true;
        this.NTF3 = true;
        this.VWF = true;
        this.CD9 = true;
        this.GAPDH = true;
        this.CD4 = true;
        this.GNB3 = true;
        this.CD163 = true;
        this.SLC2A3 = true;
        this.CD69 = true;
        this.IRAK4 = true;
        this.VDR = true;
        this.AQP5 = true;
        this.ACVRL1 = true;
        this.NFE2 = true;
        this.CD63 = true;
        this.ERBB3 = true;
        this.DDIT3 = true;
        this.IFNG = true;
        this.NTS = true;
        this.IGF1 = true;
        this.ACACB = true;
        this.TRPV4 = true;
        this.ATP2A2 = true;
        this.ALDH2 = true;
        this.NOS1 = true;
        this.PEBP1 = true;
        this.PSMD9 = true;
        this.SCARB1 = true;
        this.P2RX2 = true;
        this.ALOX5AP = true;
        this.KL = true;
        this.POSTN = true;
        this.FOXO1 = true;
        this.HTR2A = true;
        this.GPC5 = true;
        this.IRS2 = true;
        this.GAS6 = true;
        this.ANG = true;
        this.MMP14 = true;
        this.LTB4R2 = true;
        this.NFKBIA = true;
        this.BMP4 = true;
        this.RTN1 = true;
        this.PGF = true;
        this.NGB = true;
        this.AHSA1 = true;
        this.BDKRB2 = true;
        this.BDKRB1 = true;
        this.AKT1 = true;
        this.GREM1 = true;
        this.THBS1 = true;
        this.PAK6 = true;
        this.B2M = true;
        this.MYO5C = true;
        this.ONECUT1 = true;
        this.ADAM10 = true;
        this.CTSH = true;
        this.PLIN1 = true;
        this.IGF1R = true;
        this.MRPL28 = true;
        this.CACNA1H = true;
        this.PDPK1 = true;
        this.ERCC4 = true;
        this.SMG1 = true;
        this.ITGAM = true;
        this.FTO = true;
        this.MMP2 = true;
        this.SLC12A3 = true;
        this.CETP = true;
        this.CX3CL1 = true;
        this.CDH1 = true;
        this.NQO1 = true;
        this.HP = true;
        this.ZNRF1 = true;
        this.CYBA = true;
        this.TUBB3 = true;
        this.CRK = true;
        this.SERPINF2 = true;
        this.SERPINF1 = true;
        this.TRPV3 = true;
        this.CXCL16 = true;
        this.SLC2A4 = true;
        this.CD68 = true;
        this.SHBG = true;
        this.PMP22 = true;
        this.SREBF1 = true;
        this.MAPK7 = true;
        this.CCL2 = true;
        this.CCL5 = true;
        this.HNF1B = true;
        this.ERBB2 = true;
        this.FKBP10 = true;
        this.STAT5A = true;
        this.STAT3 = true;
        this.NAGLU = true;
        this.AOC2 = true;
        this.AOC3 = true;
        this.PPY = true;
        this.STH = true;
        this.ITGB3 = true;
        this.GIP = true;
        this.MPO = true;
        this.PECAM1 = true;
        this.SOX9 = true;
        this.TIMP2 = true;
        this.DCXR = true;
        this.FASN = true;
        this.COLEC12 = true;
        this.ADCYAP1 = true;
        this.SMAD7 = true;
        this.NEDD4L = true;
        this.MC4R = true;
        this.BCL2 = true;
        this.CNDP2 = true;
        this.ZNF236 = true;
        this.STK11 = true;
        this.SIRT6 = true;
        this.UHRF1 = true;
        this.TIMM44 = true;
        this.ANGPTL4 = true;
        this.DNMT1 = true;
        this.ICAM1 = true;
        this.LDLR = true;
        this.EPOR = true;
        this.PRDX2 = true;
        this.PTGER1 = true;
        this.UNC13A = true;
        this.GDF15 = true;
        this.FKBP8 = true;
        this.USF2 = true;
        this.FFAR1 = true;
        this.FFAR2 = true;
        this.NPHS1 = true;
        this.TGFB1 = true;
        this.XRCC1 = true;
        this.ERCC1 = true;
        this.GIPR = true;
        this.FGF21 = true;
        this.CLEC11A = true;
        this.FPR1 = true;
        this.TRIB3 = true;
        this.BMP2 = true;
        this.THBD = true;
        this.CST3 = true;
        this.ID1 = true;
        this.SRC = true;
        this.MAFB = true;
        this.SGK2 = true;
        this.HNF4A = true;
        this.PLTP = true;
        this.MMP9 = true;
        this.CD40 = true;
        this.PTPN1 = true;
        this.CYP24A1 = true;
        this.RCAN1 = true;
        this.ABCG1 = true;
        this.PRMT2 = true;
        this.COMT = true;
        this.MAPK1 = true;
        this.MIF = true;
        this.GGT1 = true;
        this.XBP1 = true;
        this.OSM = true;
        this.LIMK2 = true;
        this.SFI1 = true;
        this.TIMP3 = true;
        this.HMOX1 = true;
        this.APOL1 = true;
        this.MYH9 = true;
        this.PDGFB = true;
        this.ATF4 = true;
        this.TSPO = true;
        this.MIOX = true;
        this.PRDX4 = true;
        this.GK = true;
        this.RGN = true;
        this.TIMP1 = true;
        this.CLCN5 = true;
        this.AR = true;
        this.FOXO4 = true;
        this.RPS6KA6 = true;
        this.NOX1 = true;
        this.XIAP = true;
        this.CD40LG = true;
        this.L1CAM = true;
        this.IRAK1 = true;
        this.G6PD = true;
        this.F8 = true;
      }

      deselectAll(){
        this.ERRFI1 = false;
        this.MAD2L2 = false;
        this.MTHFR = false;
        this.NPPA = false;
        this.TNFRSF1B = false;
        this.PLA2G2A = false;
        this.ALPL = false;
        this.HSPG2 = false;
        this.CNR2 = false;
        this.SLC9A1 = false;
        this.COL8A2 = false;
        this.CAP1 = false;
        this.SLC2A1 = false;
        this.CYP2J2 = false;
        this.DDAH1 = false;
        this.CYR61 = false;
        this.NGF = false;
        this.HMGCS2 = false;
        this.CTSS = false;
        this.S100A12 = false;
        this.LMNA = false;
        this.CD247 = false;
        this.SELE = false;
        this.FMO3 = false;
        this.PRDX6 = false;
        this.GLUL = false;
        this.LAMC1 = false;
        this.PTGS2 = false;
        this.CHI3L1 = false;
        this.CHIT1 = false;
        this.FMOD = false;
        this.IL10 = false;
        this.PFKFB2 = false;
        this.CD34 = false;
        this.COG2 = false;
        this.NLRP3 = false;
        this.ROCK2 = false;
        this.APOB = false;
        this.POMC = false;
        this.GCKR = false;
        this.PLEKHH2 = false;
        this.PRKCE = false;
        this.PIGF = false;
        this.MSH2 = false;
        this.GFPT1 = false;
        this.TACR1 = false;
        this.REG1A = false;
        this.EIF2AK3 = false;
        this.ADRA2B = false;
        this.IL1B = false;
        this.PROC = false;
        this.POLR2D = false;
        this.ZEB2 = false;
        this.ACVR1C = false;
        this.DPP4 = false;
        this.NFE2L2 = false;
        this.IGFBP5 = false;
        this.CCL20 = false;
        this.HDAC4 = false;
        this.CAPN10 = false;
        this.GHRL = false;
        this.PPARG = false;
        this.RAF1 = false;
        this.MYD88 = false;
        this.CX3CR1 = false;
        this.CCK = false;
        this.EXOSC7 = false;
        this.CCR1 = false;
        this.CCR5 = false;
        this.GPX1 = false;
        this.RHOA = false;
        this.CISH = false;
        this.TKT = false;
        this.APPL1 = false;
        this.SLMAP = false;
        this.COL8A1 = false;
        this.CD47 = false;
        this.GAP43 = false;
        this.CD80 = false;
        this.RHO = false;
        this.TRH = false;
        this.TF = false;
        this.RBP1 = false;
        this.TRPC1 = false;
        this.AGTR1 = false;
        this.SUCNR1 = false;
        this.P2RY1 = false;
        this.MME = false;
        this.SLC2A2 = false;
        this.PIK3CA = false;
        this.PARL = false;
        this.AHSG = false;
        this.ADIPOQ = false;
        this.SPON2 = false;
        this.WFS1 = false;
        this.CD38 = false;
        this.PROM1 = false;
        this.PPARGC1A = false;
        this.IGFBP7 = false;
        this.CXCL5 = false;
        this.CXCL9 = false;
        this.CXCL10 = false;
        this.CXCL11 = false;
        this.HPSE = false;
        this.SPP1 = false;
        this.ADH1B = false;
        this.EGF = false;
        this.ALPK1 = false;
        this.FABP2 = false;
        this.PDE5A = false;
        this.SETD7 = false;
        this.SMAD1 = false;
        this.EDNRA = false;
        this.NR3C2 = false;
        this.TLR2 = false;
        this.NPY5R = false;
        this.FBXO8 = false;
        this.VEGFC = false;
        this.ACSL1 = false;
        this.SORBS2 = false;
        this.F11 = false;
        this.BASP1 = false;
        this.PTGER4 = false;
        this.PRKAA1 = false;
        this.GHR = false;
        this.ITGA2 = false;
        this.CDK7 = false;
        this.F2R = false;
        this.ERAP2 = false;
        this.APC = false;
        this.TNFAIP8 = false;
        this.VDAC1 = false;
        this.PDGFRB = false;
        this.CD74 = false;
        this.SPARC = false;
        this.EBF1 = false;
        this.GFPT2 = false;
        this.RREB1 = false;
        this.EDN1 = false;
        this.CDKAL1 = false;
        this.HFE = false;
        this.HLA_A = false;
        this.LTA = false;
        this.TNF = false;
        this.HSPA1A = false;
        this.HSPA1B = false;
        this.HLA_DQA1 = false;
        this.MAPK14 = false;
        this.CDKN1A = false;
        this.GLO1 = false;
        this.VEGFA = false;
        this.CD2AP = false;
        this.CNR1 = false;
        this.ENPP1 = false;
        this.CTGF = false;
        this.RPS12 = false;
        this.SGK1 = false;
        this.MAP3K5 = false;
        this.CITED2 = false;
        this.UTRN = false;
        this.MTHFD1L = false;
        this.VIP = false;
        this.SOD2 = false;
        this.LPA = false;
        this.THBS2 = false;
        this.PDGFA = false;
        this.IL6 = false;
        this.NPY = false;
        this.JAZF1 = false;
        this.CPVL = false;
        this.AQP1 = false;
        this.ELMO1 = false;
        this.IGFBP3 = false;
        this.EGFR = false;
        this.ELN = false;
        this.NCF1 = false;
        this.HSPB1 = false;
        this.SEMA3A = false;
        this.PON3 = false;
        this.PON2 = false;
        this.NAMPT = false;
        this.CAV1 = false;
        this.LEP = false;
        this.AKR1B1 = false;
        this.AKR1B10 = false;
        this.PIP = false;
        this.RARRES2 = false;
        this.NOS3 = false;
        this.ANGPT2 = false;
        this.DEFA1 = false;
        this.LPL = false;
        this.EBF2 = false;
        this.ADRB3 = false;
        this.EIF4EBP1 = false;
        this.FGFR1 = false;
        this.CRH = false;
        this.SGK3 = false;
        this.FABP5 = false;
        this.FABP4 = false;
        this.MMP16 = false;
        this.NCALD = false;
        this.KLF10 = false;
        this.ENPP2 = false;
        this.PVT1 = false;
        this.JAK2 = false;
        this.PSIP1 = false;
        this.PLIN2 = false;
        this.RPS6 = false;
        this.ALDH1A1 = false;
        this.FRMD3 = false;
        this.GAS1 = false;
        this.BAAT = false;
        this.ABCA1 = false;
        this.TXN = false;
        this.AMBP = false;
        this.C5 = false;
        this.HSPA5 = false;
        this.ANGPTL2 = false;
        this.PTGES = false;
        this.TSC1 = false;
        this.ABO = false;
        this.ADAMTS13 = false;
        this.PTGDS = false;
        this.KLF6 = false;
        this.CDC123 = false;
        this.BAMBI = false;
        this.CXCL12 = false;
        this.MBL2 = false;
        this.TFAM = false;
        this.SIRT1 = false;
        this.SRGN = false;
        this.UNC5B = false;
        this.ADK = false;
        this.PTEN = false;
        this.RBP4 = false;
        this.CYP2C19 = false;
        this.ENTPD1 = false;
        this.TCF7L2 = false;
        this.BNIP3 = false;
        this.IGF2 = false;
        this.INS = false;
        this.TH = false;
        this.KCNQ1 = false;
        this.HBG2 = false;
        this.SMPD1 = false;
        this.ILK = false;
        this.ADM = false;
        this.PTH = false;
        this.NUCB2 = false;
        this.KCNJ11 = false;
        this.SAA1 = false;
        this.BDNF = false;
        this.WT1 = false;
        this.CD59 = false;
        this.PDHX = false;
        this.TRAF6 = false;
        this.API5 = false;
        this.NR1H3 = false;
        this.NDUFS3 = false;
        this.FOLH1 = false;
        this.APLNR = false;
        this.P2RX3 = false;
        this.CNTF = false;
        this.FADS1 = false;
        this.FADS2 = false;
        this.FKBP2 = false;
        this.SYVN1 = false;
        this.PC = false;
        this.DHCR7 = false;
        this.PRCP = false;
        this.NOX4 = false;
        this.PDGFD = false;
        this.ATM = false;
        this.IL18 = false;
        this.APOA1 = false;
        this.HYOU1 = false;
        this.ESAM = false;
        this.FKBP4 = false;
        this.FGF23 = false;
        this.NTF3 = false;
        this.VWF = false;
        this.CD9 = false;
        this.GAPDH = false;
        this.CD4 = false;
        this.GNB3 = false;
        this.CD163 = false;
        this.SLC2A3 = false;
        this.CD69 = false;
        this.IRAK4 = false;
        this.VDR = false;
        this.AQP5 = false;
        this.ACVRL1 = false;
        this.NFE2 = false;
        this.CD63 = false;
        this.ERBB3 = false;
        this.DDIT3 = false;
        this.IFNG = false;
        this.NTS = false;
        this.IGF1 = false;
        this.ACACB = false;
        this.TRPV4 = false;
        this.ATP2A2 = false;
        this.ALDH2 = false;
        this.NOS1 = false;
        this.PEBP1 = false;
        this.PSMD9 = false;
        this.SCARB1 = false;
        this.P2RX2 = false;
        this.ALOX5AP = false;
        this.KL = false;
        this.POSTN = false;
        this.FOXO1 = false;
        this.HTR2A = false;
        this.GPC5 = false;
        this.IRS2 = false;
        this.GAS6 = false;
        this.ANG = false;
        this.MMP14 = false;
        this.LTB4R2 = false;
        this.NFKBIA = false;
        this.BMP4 = false;
        this.RTN1 = false;
        this.PGF = false;
        this.NGB = false;
        this.AHSA1 = false;
        this.BDKRB2 = false;
        this.BDKRB1 = false;
        this.AKT1 = false;
        this.GREM1 = false;
        this.THBS1 = false;
        this.PAK6 = false;
        this.B2M = false;
        this.MYO5C = false;
        this.ONECUT1 = false;
        this.ADAM10 = false;
        this.CTSH = false;
        this.PLIN1 = false;
        this.IGF1R = false;
        this.MRPL28 = false;
        this.CACNA1H = false;
        this.PDPK1 = false;
        this.ERCC4 = false;
        this.SMG1 = false;
        this.ITGAM = false;
        this.FTO = false;
        this.MMP2 = false;
        this.SLC12A3 = false;
        this.CETP = false;
        this.CX3CL1 = false;
        this.CDH1 = false;
        this.NQO1 = false;
        this.HP = false;
        this.ZNRF1 = false;
        this.CYBA = false;
        this.TUBB3 = false;
        this.CRK = false;
        this.SERPINF2 = false;
        this.SERPINF1 = false;
        this.TRPV3 = false;
        this.CXCL16 = false;
        this.SLC2A4 = false;
        this.CD68 = false;
        this.SHBG = false;
        this.PMP22 = false;
        this.SREBF1 = false;
        this.MAPK7 = false;
        this.CCL2 = false;
        this.CCL5 = false;
        this.HNF1B = false;
        this.ERBB2 = false;
        this.FKBP10 = false;
        this.STAT5A = false;
        this.STAT3 = false;
        this.NAGLU = false;
        this.AOC2 = false;
        this.AOC3 = false;
        this.PPY = false;
        this.STH = false;
        this.ITGB3 = false;
        this.GIP = false;
        this.MPO = false;
        this.PECAM1 = false;
        this.SOX9 = false;
        this.TIMP2 = false;
        this.DCXR = false;
        this.FASN = false;
        this.COLEC12 = false;
        this.ADCYAP1 = false;
        this.SMAD7 = false;
        this.NEDD4L = false;
        this.MC4R = false;
        this.BCL2 = false;
        this.CNDP2 = false;
        this.ZNF236 = false;
        this.STK11 = false;
        this.SIRT6 = false;
        this.UHRF1 = false;
        this.TIMM44 = false;
        this.ANGPTL4 = false;
        this.DNMT1 = false;
        this.ICAM1 = false;
        this.LDLR = false;
        this.EPOR = false;
        this.PRDX2 = false;
        this.PTGER1 = false;
        this.UNC13A = false;
        this.GDF15 = false;
        this.FKBP8 = false;
        this.USF2 = false;
        this.FFAR1 = false;
        this.FFAR2 = false;
        this.NPHS1 = false;
        this.TGFB1 = false;
        this.XRCC1 = false;
        this.ERCC1 = false;
        this.GIPR = false;
        this.FGF21 = false;
        this.CLEC11A = false;
        this.FPR1 = false;
        this.TRIB3 = false;
        this.BMP2 = false;
        this.THBD = false;
        this.CST3 = false;
        this.ID1 = false;
        this.SRC = false;
        this.MAFB = false;
        this.SGK2 = false;
        this.HNF4A = false;
        this.PLTP = false;
        this.MMP9 = false;
        this.CD40 = false;
        this.PTPN1 = false;
        this.CYP24A1 = false;
        this.RCAN1 = false;
        this.ABCG1 = false;
        this.PRMT2 = false;
        this.COMT = false;
        this.MAPK1 = false;
        this.MIF = false;
        this.GGT1 = false;
        this.XBP1 = false;
        this.OSM = false;
        this.LIMK2 = false;
        this.SFI1 = false;
        this.TIMP3 = false;
        this.HMOX1 = false;
        this.APOL1 = false;
        this.MYH9 = false;
        this.PDGFB = false;
        this.ATF4 = false;
        this.TSPO = false;
        this.MIOX = false;
        this.PRDX4 = false;
        this.GK = false;
        this.RGN = false;
        this.TIMP1 = false;
        this.CLCN5 = false;
        this.AR = false;
        this.FOXO4 = false;
        this.RPS6KA6 = false;
        this.NOX1 = false;
        this.XIAP = false;
        this.CD40LG = false;
        this.L1CAM = false;
        this.IRAK1 = false;
        this.G6PD = false;
        this.F8 = false;
      }

}
