# Generated by Django 4.1 on 2022-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=500)),
            ],
        ),
    ]
