# Generated by Django 4.1 on 2022-08-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gtex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elementi',
        ),
    ]
