# Generated by Django 4.1 on 2022-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gtex', '0002_delete_elementi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneMedianTpm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('adipose_subcutaneous', models.FloatField(blank=True, db_column='Adipose - Subcutaneous', null=True)),
                ('adipose_visceral_omentum_field', models.FloatField(blank=True, db_column='Adipose - Visceral (Omentum)', null=True)),
                ('adrenal_gland', models.FloatField(blank=True, db_column='Adrenal Gland', null=True)),
                ('artery_aorta', models.FloatField(blank=True, db_column='Artery - Aorta', null=True)),
                ('artery_coronary', models.FloatField(blank=True, db_column='Artery - Coronary', null=True)),
                ('artery_tibial', models.FloatField(blank=True, db_column='Artery - Tibial', null=True)),
                ('bladder', models.FloatField(blank=True, db_column='Bladder', null=True)),
                ('brain_amygdala', models.FloatField(blank=True, db_column='Brain - Amygdala', null=True)),
                ('brain_anterior_cingulate_cortex_ba24_field', models.FloatField(blank=True, db_column='Brain - Anterior cingulate cortex (BA24)', null=True)),
                ('brain_caudate_basal_ganglia_field', models.FloatField(blank=True, db_column='Brain - Caudate (basal ganglia)', null=True)),
                ('brain_cerebellar_hemisphere', models.FloatField(blank=True, db_column='Brain - Cerebellar Hemisphere', null=True)),
                ('brain_cerebellum', models.FloatField(blank=True, db_column='Brain - Cerebellum', null=True)),
                ('brain_cortex', models.FloatField(blank=True, db_column='Brain - Cortex', null=True)),
                ('brain_frontal_cortex_ba9_field', models.FloatField(blank=True, db_column='Brain - Frontal Cortex (BA9)', null=True)),
                ('brain_hippocampus', models.FloatField(blank=True, db_column='Brain - Hippocampus', null=True)),
                ('brain_hypothalamus', models.FloatField(blank=True, db_column='Brain - Hypothalamus', null=True)),
                ('brain_nucleus_accumbens_basal_ganglia_field', models.FloatField(blank=True, db_column='Brain - Nucleus accumbens (basal ganglia)', null=True)),
                ('brain_putamen_basal_ganglia_field', models.FloatField(blank=True, db_column='Brain - Putamen (basal ganglia)', null=True)),
                ('brain_spinal_cord_cervical_c_1_field', models.FloatField(blank=True, db_column='Brain - Spinal cord (cervical c-1)', null=True)),
                ('brain_substantia_nigra', models.FloatField(blank=True, db_column='Brain - Substantia nigra', null=True)),
                ('breast_mammary_tissue', models.FloatField(blank=True, db_column='Breast - Mammary Tissue', null=True)),
                ('cells_cultured_fibroblasts', models.FloatField(blank=True, db_column='Cells - Cultured fibroblasts', null=True)),
                ('cells_ebv_transformed_lymphocytes', models.FloatField(blank=True, db_column='Cells - EBV-transformed lymphocytes', null=True)),
                ('cervix_ectocervix', models.FloatField(blank=True, db_column='Cervix - Ectocervix', null=True)),
                ('cervix_endocervix', models.FloatField(blank=True, db_column='Cervix - Endocervix', null=True)),
                ('colon_sigmoid', models.FloatField(blank=True, db_column='Colon - Sigmoid', null=True)),
                ('colon_transverse', models.FloatField(blank=True, db_column='Colon - Transverse', null=True)),
                ('esophagus_gastroesophageal_junction', models.FloatField(blank=True, db_column='Esophagus - Gastroesophageal Junction', null=True)),
                ('esophagus_mucosa', models.FloatField(blank=True, db_column='Esophagus - Mucosa', null=True)),
                ('esophagus_muscularis', models.FloatField(blank=True, db_column='Esophagus - Muscularis', null=True)),
                ('fallopian_tube', models.FloatField(blank=True, db_column='Fallopian Tube', null=True)),
                ('heart_atrial_appendage', models.FloatField(blank=True, db_column='Heart - Atrial Appendage', null=True)),
                ('heart_left_ventricle', models.FloatField(blank=True, db_column='Heart - Left Ventricle', null=True)),
                ('kidney_cortex', models.FloatField(blank=True, db_column='Kidney - Cortex', null=True)),
                ('kidney_medulla', models.FloatField(blank=True, db_column='Kidney - Medulla', null=True)),
                ('liver', models.FloatField(blank=True, db_column='Liver', null=True)),
                ('lung', models.FloatField(blank=True, db_column='Lung', null=True)),
                ('minor_salivary_gland', models.FloatField(blank=True, db_column='Minor Salivary Gland', null=True)),
                ('muscle_skeletal', models.FloatField(blank=True, db_column='Muscle - Skeletal', null=True)),
                ('nerve_tibial', models.FloatField(blank=True, db_column='Nerve - Tibial', null=True)),
                ('ovary', models.FloatField(blank=True, db_column='Ovary', null=True)),
                ('pancreas', models.FloatField(blank=True, db_column='Pancreas', null=True)),
                ('pituitary', models.FloatField(blank=True, db_column='Pituitary', null=True)),
                ('prostate', models.FloatField(blank=True, db_column='Prostate', null=True)),
                ('skin_not_sun_exposed_suprapubic_field', models.FloatField(blank=True, db_column='Skin - Not Sun Exposed (Suprapubic)', null=True)),
                ('skin_sun_exposed_lower_leg_field', models.FloatField(blank=True, db_column='Skin - Sun Exposed (Lower leg)', null=True)),
                ('small_intestine_terminal_ileum', models.FloatField(blank=True, db_column='Small Intestine - Terminal Ileum', null=True)),
                ('spleen', models.FloatField(blank=True, db_column='Spleen', null=True)),
                ('stomach', models.FloatField(blank=True, db_column='Stomach', null=True)),
                ('testis', models.FloatField(blank=True, db_column='Testis', null=True)),
                ('thyroid', models.FloatField(blank=True, db_column='Thyroid', null=True)),
                ('uterus', models.FloatField(blank=True, db_column='Uterus', null=True)),
                ('vagina', models.FloatField(blank=True, db_column='Vagina', null=True)),
                ('whole_blood', models.FloatField(blank=True, db_column='Whole Blood', null=True)),
            ],
            options={
                'db_table': 'gene_median_tpm',
                'managed': False,
            },
        ),
    ]
