# Generated by Django 4.1 on 2022-08-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gtex', '0004_sampleattributesds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPhenotypesDd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subjid', models.CharField(blank=True, db_column='SUBJID', max_length=50, null=True)),
                ('sex', models.IntegerField(blank=True, db_column='SEX', null=True)),
                ('age', models.CharField(blank=True, db_column='AGE', max_length=50, null=True)),
                ('dthhrdy', models.IntegerField(blank=True, db_column='DTHHRDY', null=True)),
            ],
            options={
                'db_table': 'subject_phenotypes_dd',
                'managed': False,
            },
        ),
    ]
