# Generated by Django 3.2.15 on 2022-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gtex', '0005_subjectphenotypesdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TissueLiver',
            fields=[
                ('gene', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('valore_p', models.FloatField(blank=True, null=True)),
                ('agg_valore_p', models.FloatField(blank=True, db_column='agg_valore_P', null=True)),
                ('logfc', models.CharField(blank=True, db_column='LogFC', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tissue_liver',
                'managed': False,
            },
        ),
    ]
