# Generated by Django 3.2.15 on 2022-09-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gtex', '0007_auto_20220917_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaTabelle',
            fields=[
                ('tessuto', models.CharField(db_column='Tessuto', max_length=36)),
                ('tabella', models.CharField(db_column='Tabella', max_length=35, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lista_tabelle',
                'managed': False,
            },
        ),
    ]
